### ISSUE TITLE
SwingFXUtils.toFXImage() possibly not blacking out destination pixels

### ISSUE THREAD

**Issue by Xantix** [Debian/openjfx#1]
Is the following a bug in SwingFXUtils.toFXImage?

When converting a BufferedImage to an FxImage, when given a non-null FxImage parameter of sufficient size, it writes over the data in the FxImage.

However, it looks like there is a bug when the FxImage is larger than the BufferedImage.

I presume that the intended behavior is to paint the surrounding pixels in the FxImage black, but as you can see on lines 107, 111, and 114, we:

1. Create an *empty[]* of length *iw*
2. Use *PixelWriter.setPixels()* to paint all columns to the right of the source's width using data from *empty*
3. Use *PixelWriter.setPixels()* to paint all rows below the source's height using data from *empty*.

It looks like the empty[] is the wrong size.

For example in step 2:

If the BufferedImage is 500 x 500, and FxImage is 1000 x 1000, then instead of filling all of the 500 x 1000 right hand side of the image with black, we only fill 1000 of those pixels with black; i.e. most of the original pixel data remains and is not replaced with black.

The same example applies to step 3.

(It's possible I'm mistaken and that the setPixel() function has a defined behavior when given a buffer smaller than the region to set...but the docs didn't mention that explicitly, and I would expect it to stop painting pixels when it reaches the end of the buffer instead of starting over at the beginning of the buffer until the region is full).

(It looks like the FromFxImage() function handles this case differently, choosing instead to first paint the *entire* destination black -- line 250)

**Comment by ebourg** [comment]
Hi, this repository is only about the packaging of OpenJFX in Debian. If you need help with your JavaFX code you should ask on StackOverflow or on the OpenJFX mailing list (http://mail.openjdk.java.net/mailman/listinfo/openjfx-dev).
